# Generated by Django 6.0.3 on 2026-06-21 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
