# Generated by Django 6.0.3 on 2026-06-21 04:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'METODO_PAGO',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(default='Consumidor Final', max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('email_cliente', models.EmailField(default='noreply@abaddon.com', max_length=254)),
                ('tipo_venta', models.CharField(choices=[('Cotiza', 'Cotiza Online'), ('Presencial', 'Venta en Tienda')], default='Cotiza', max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.CASCADE, to='Ventas.metodopago')),
            ],
            options={
                'db_table': 'VENTA',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ventas.venta')),
            ],
            options={
                'db_table': 'DETALLE_VENTA',
            },
        ),
    ]
